### ISSUE TITLE
Import Button should be highlighted after the user browses the Publish settings file

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#108]
When the user sign in the subscription through the publish settings file,
Clicks on browse Button.
Selects the proper file of the publish settings.
Import Button should be highlighted after the file selection.
In this case the Browse button is highlighted.
PFB the screen shot.

![browsesubscription](https://cloud.githubusercontent.com/assets/10046647/5851906/0ef793ea-a234-11e4-9847-4a189b439782.png)

**Comment by BeatriceOltean** [comment]
Let's make the Import the default bttn on the dialog.

**Comment by kasturiswain** [comment]
Import Button is high lighted, but the default button is still the 'browse' button after the user browses the publish setting file.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
