### ISSUE TITLE
Plug in Clearing the Subscription when user selecting 'NO' button from key board

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#109]
Click on 'Clear Subscriptions'.
Press TAB from the Key board.
'NO' button is getting highlighted.
Press ENTER from the Key board.
It is clearing the subscriptions.
But when the user Clicks on the 'NO' button Manually, it is not clearing the subscriptions.

PFB the screen shot.
![clearsub](https://cloud.githubusercontent.com/assets/10046647/5851956/f2b157ce-a234-11e4-8028-eed7e9451397.png)

**Comment by BeatriceOltean** [comment]
Enter will effect on the default button for the dialog. This is a bug only if pressing No clears the subscription

**Comment by BeatriceOltean** [comment]
This is the expected behavior and aligned with IntelliJ IDE behavior
