### ISSUE TITLE
Services Explorer root node should be set to azure

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#11]
We need following changes to the current services explorer menu. Layering @avranju's proposed design here. 

Services Explorer
=================
Azure                 
  +                   
  +-+ Mobile Services 
  |                   
  +-+ Virtual Machines
  |                   
  +-+ Cloud Services  

Office 365            
  +                   
  +-+ Exchange        
  |                   
  +-+ Files           

Bing Services         
  +                   
  +-+ Maps            
  |                   
  +-+ Search

**Comment by kasturiswain** [comment]
This is working as expected in the latest build.
