### ISSUE TITLE
ENTER key from key board is not working for Dialogue Boxes

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#110]
When the Close button is highlighted in the window and the user presses the ENTER key from the Key board, it should close the window.
But it is not closing the window.
PFB the screen shot.

![closewindow](https://cloud.githubusercontent.com/assets/10046647/5852045/524a3e66-a236-11e4-93cb-0367b56a8604.png)

**Comment by leotilli** [comment]
This is the default swing behavior
