### ISSUE TITLE
Plugin should enable the start button when the machine is shut down 

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#111]
1. Connect to the Remote Desktop from plugin.
2. Shut down the Remote Desktop manually.

In the portal it is showing that the system is shut down and start button is enabled.
PFB the screen shot.
![portal](https://cloud.githubusercontent.com/assets/10046647/5873410/1ce6819e-a31c-11e4-8950-48fb763b407f.png)

But the plug does not show that the remote desktop is shut down and the shut down button is enabled.
PFB the screen shot.
![puginrefresh](https://cloud.githubusercontent.com/assets/10046647/5873436/5fb8b05a-a31c-11e4-83dd-0711311a1939.png)

**Comment by BeatriceOltean** [comment]
Would you please check that Refresh is updating the status correctly ?

**Comment by kasturiswain** [comment]
After clicking refresh button in the plugin, it is not updating the status.

**Comment by akrakovsky** [comment]
I could not reproduce this issue. Visual Studio and IntelliJ both refresh the shut down of the VM a few seconds later than the portal, but that's the only thing I detected.

**Comment by kasturiswain** [comment]
In the 23rd Jan build I am able to reproduce this issue.I am not able to reproduce this issue in the latest build.
