### ISSUE TITLE
Plugin throwing Exception when user start/shutdown/restart the system from portal and then through plug in

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#112]
When start/shut down/restart button is clicked  from the plugin and then the same is clicked from the azure portal, then it shows the error message as “Failed to start”. 
PFB the screen shot.

![strtfrmportal](https://cloud.githubusercontent.com/assets/10046647/5873477/ed85524e-a31c-11e4-8499-5a4a892c3360.png)

When start/shut down/restart button is clicked  from the azure portal and refresh button is not clicked in the plugin and the same start/Shutdown button is clicked from plugin, then it is not showing any proper error message.
 PFB the screen shot.

![strtfrmplugin](https://cloud.githubusercontent.com/assets/10046647/5873478/f1d247d0-a31c-11e4-8d71-6c66227d9d52.png)

**Comment by BeatriceOltean** [comment]
This is similar behavior. The only difference is the text message Failed to start versus error starting VM. The behavior is the same and we want to shoe the exception.
