### ISSUE TITLE
Include date in the VM name

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#116]
When listing VM names right now only the month and the year is displayed along with the name. Please include the date as well. The idea is to be able to pick the latest VM just by looking at the list instead of having to click on each one. Since there are multiple releases of an image in a single month we might want to add the date as well.

![image](https://cloud.githubusercontent.com/assets/628128/5969749/9daa64ac-a7dc-11e4-8964-f142df8551e5.png)

**Comment by kasturiswain** [comment]
This is fixed and working as expected in the latest build.
