### ISSUE TITLE
Show Linux VMs under categorized by Linux distribution instead of "Other"?

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#117]
All the Linux images are under the "Other" category. Can we not categorize them by Linux distribution (Ubuntu, CentOS, CoreOS etc.)?

**Comment by BeatriceOltean** [comment]
Decided to have a Linux category and have Others category. This one should be part of the Linux group

**Comment by kasturiswain** [comment]
This is fixed and working as expected in the latest build.
