### ISSUE TITLE
Select newly created cloud service in the drop down after it is created

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#120]
When you create a new cloud service, we should select that new service in the drop down after the service is created. Also, we should default to creating a new cloud service instead of selecting one.

![image](https://cloud.githubusercontent.com/assets/628128/5969884/0272a30c-a7df-11e4-9d16-4dbec78284f6.png)

**Comment by avranju** [comment]
I was checking what the UX is in VS. So with a new VM you first see a screen such as this:

![image](https://cloud.githubusercontent.com/assets/628128/5982889/ec0cd832-a87c-11e4-8b37-4d2d7756c42a.png)

When you click on the drop down on the *Cloud Service* field you see this:

![image](https://cloud.githubusercontent.com/assets/628128/5982903/025cb31e-a87d-11e4-89dd-b65b0a775f8f.png)

After a while, if you leave the drop down open, then the cloud services get loaded:

![image](https://cloud.githubusercontent.com/assets/628128/5982910/1417569a-a87d-11e4-8de3-08ff3e526936.png)

If you click *<Create new...>* and create a new cloud service then after the cloud service has been created, that gets pre-selected in the drop down:

![image](https://cloud.githubusercontent.com/assets/628128/5982937/4b5ea2f2-a87d-11e4-8cdb-cb75784fa494.png)

I think this is a reasonable flow that we can adopt as well.

**Comment by kasturiswain** [comment]
This is fixed and working as expected in the latest build.
