### ISSUE TITLE
Factor out implementation of "Create new" item in drop downs

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#121]
We seem to have multiple instances of drop downs which need a sentinel "Create" item artificially inserted into the list (the cloud service drop down and storage drop down are examples). I am wondering if it'll make sense to make a reusable component that has built-in support for such an item and use that everywhere we need it instead of implementing it afresh each time.

**Comment by martinsawicki** [comment]
obsolete
