### ISSUE TITLE
Use ListCellRenderer instead of ListCellRendererWrapper or ColoredListCellRenderer?

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#122]
An IntelliJ inspection complains that using a ListCellRenderer derived class can cause rendering issues on GTK+. Should we consider using ListCellRendererWrapper or ColoredListCellRenderer?

**Comment by kasturiswain** [comment]
Following are the occurrences of  ListCellRenderer Class in the Latest build.
![listcellrenderer](https://cloud.githubusercontent.com/assets/10046647/6436194/6796462a-c0d1-11e4-9d2b-e25540b5ec23.png)

**Comment by BeatriceOltean** [comment]
The class is ListCellRendererWrapper; so no longer occurrences of ListCellRenderer.
