### ISSUE TITLE
Factor out code for hiding the "Help" button in wizards into a common utility routine

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#123]
Factor out code for hiding the "Help" button in wizards into a common utility routine and invoke that instead of duplicating code in multiple places. Also document the reason why the implementation looks the way it does as comments in the source.

**Comment by leotilli** [comment]
This particular item could be addressed now, but if we implement a custom wizard (based on the current one),  we might be able to address it together with issues #139 and #183

**Comment by martinsawicki** [comment]
obsolete
