### ISSUE TITLE
Plug in throwing Exception while Creating the VM

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#124]
Click on create VM
Give all the valid details
Click on Finish

It is throwing the following Exception.
![notabletocreatevm](https://cloud.githubusercontent.com/assets/10046647/5973848/2a020b88-a893-11e4-9083-7ec2bae2e371.png)

**Comment by BeatriceOltean** [comment]
Need to validate and see if the cloud service has already a VM associated; need to filter cloud services

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
