### ISSUE TITLE
Plugin allowing same End Point name more than once

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#126]
<b>Environment: </b>Windows/IntelliJ14

Azure portal does not allow same End Point name twice and shows error message.
PFB the screen shot.
![portal7](https://cloud.githubusercontent.com/assets/10046647/5974034/a15ea0fe-a895-11e4-97d9-877f8fd15970.png)

Plugin allowing same End Point name more than once.
PFB the screen shot.
![plugin7](https://cloud.githubusercontent.com/assets/10046647/5974047/ce73b20a-a895-11e4-9ac3-0533147fecaf.png)

**Comment by akrakovsky** [comment]
I couldn't reproduce this issue. Can you send me the steps, or maybe a video showing how you reach this state?

**Comment by kasturiswain** [comment]
Steps in portal

Create new VM.
Give the VM Configuration details.
Click Next.
Select duplicate end points.
Change one of the endpoint name.
It will not allow to move forward to the next window.In portal it is showing error message near the public port number and private port number as well.
PFB the screen shot.
![portal](https://cloud.githubusercontent.com/assets/10046647/6015041/709aae42-ab95-11e4-8bc1-e8cea5cd1cc6.png)

Steps in plugin

Create new VM.
Give subscription details.
Give image details..
Give VM setting details.
Give Cloud service details.
Select duplicate end points.
Change one of the endpoint name.
Click some where else in the screen.
It will allow to Finish the VM creation.In plugin it is not showing error message near the public port number and private port number.
PFB the screen shot.
![plugin](https://cloud.githubusercontent.com/assets/10046647/6015125/afabf856-ab96-11e4-9755-838a2cdf68dc.png)

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
