### ISSUE TITLE
Plugin not allowing to create the availability set or select 'NONE'

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#128]
<b>Environment: </b>Windows/IntelliJ14

Portal allows to select the availability set as 'NONE' or create a new Availability Set.
PFB the screen shot.
![portal5](https://cloud.githubusercontent.com/assets/10046647/5974339/5a2abd54-a899-11e4-9ded-95ea507643d5.png)
Plugin not allowing to select the availability set as 'NONE' or create a new Availability Set.
PFB the screen shot.
![plugin5](https://cloud.githubusercontent.com/assets/10046647/5974352/7dc3b6c6-a899-11e4-90eb-e06654f3c2fd.png)

**Comment by BeatriceOltean** [comment]
This is the same with VS
