### ISSUE TITLE
For Creating the VM the name are different in story board and in plug in

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#129]
<b>Environment: </b>Windows/IntelliJ14

For Creating the VM the name in plug in is Create VM.
PFB the screen shot.
![plugincreatevm](https://cloud.githubusercontent.com/assets/10046647/5974623/5ee34070-a89c-11e4-8d8b-676e419d8cf5.png)
For Creating the VM the name in story board is Create Virtual Machine.
PFB the screen shot.
![storyboardcreatevm](https://cloud.githubusercontent.com/assets/10046647/5974630/6ad10552-a89c-11e4-9fac-30939a090515.png)

**Comment by BeatriceOltean** [comment]
I'm fine with Create VM
