### ISSUE TITLE
UI Alignment issues in Error dialogs

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#13]
We see few UI Issues in error dialogs that needs to be corrected. Attached below some of the sample error screenshots. 

![image](https://cloud.githubusercontent.com/assets/1501823/5038237/62c3c002-6b43-11e4-96fe-40fa124f3847.png)

![image](https://cloud.githubusercontent.com/assets/1501823/5038246/7c12d58e-6b43-11e4-9517-a21a230ad382.png)

![image](https://cloud.githubusercontent.com/assets/1501823/5038264/96f66528-6b43-11e4-863a-28c801e9146a.png)

**Comment by babumuralidharan** [comment]
@kasturiswain Can you check this ??

**Comment by kasturiswain** [comment]
This issue is fixed in the latest build.
