### ISSUE TITLE
Add support for virtual networks and subnet selection while creating VMs?

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#130]
When creating a VM today there's no support for having the VM created in a vnet. Should we have this added?

**Comment by leotilli** [comment]
The Azure SDK for Java provides properties to specify a Virtual Network when creating a VM, but unfortunately I cannot find the API method to list existing Virtual Networks.
The REST API exposes the following method https://msdn.microsoft.com/en-us/library/azure/jj157185.aspx but I cannot find any VirtualNetworkOperations class in the SDK for Java.

**Comment by avranju** [comment]
Doesn't the [NetworkOperations](https://github.com/Azure/azure-sdk-for-java/blob/8eefa8ffe22e51fbb93a0d6dea9d5e842f4ebd60/management-network/src/main/java/com/microsoft/windowsazure/management/network/NetworkOperations.java) type provide this support?

**Comment by leotilli** [comment]
It exposes the list operation, so I'll try using it.

**Comment by kasturiswain** [comment]
This issue is reproducible in the latest build.
PFB the screen shot.
![snap](https://cloud.githubusercontent.com/assets/10046647/6343743/3c869258-bc14-11e4-9ba5-095cd0a92795.png)

**Comment by avranju** [comment]
This was not merged into the build yesterday due to an error. I'll add you to the build notification mailing list so when you see a build failure email you'll know that the day's commits didn't make into the build.

**Comment by kasturiswain** [comment]
Getting the below error message when trying to create VM.
![vmerror](https://cloud.githubusercontent.com/assets/10046647/6369647/4cb0f1be-bd0e-11e4-9418-49c0eaa8cfbd.png)

**Comment by avranju** [comment]
This was an issue with a missing line in the ant build. Have addressed it now. This should be testable in today's build.

**Comment by kasturiswain** [comment]
virtual networks and subnet Buttons are disabled.
![vmsunnet](https://cloud.githubusercontent.com/assets/10046647/6435623/f82e33a0-c0c7-11e4-911c-e1f43396efa1.png)
In the portal virtual networks option is showing the data while craeting the VM.
![vmportal](https://cloud.githubusercontent.com/assets/10046647/6435699/6076b288-c0c9-11e4-80a1-b90ff15c34b2.png)

**Comment by leotilli** [comment]
Virtual Networks are associated to Deployments, and Subnets to Virtual Machines. When you have a Cloud Service that already has a VM, it means that there's already a Production Deployment configured, and the VNet associated to it cannot be changed.
In order to test this, you should use an empty CS and make sure it let's you choose a VNet in the same region. Once you do that, and create the VM, that CS will have the selected VNet fixed.
We'll probably modify the UI in a future release to make this self-explanatory.

**Comment by babumuralidharan** [comment]
@avranju, @BeatriceOltean,@leotilli, can we allow vnet creation in our plugin which would be a good improvement from VS ?

**Comment by babumuralidharan** [comment]
Closing this issue as we are tracking vnet create in another issue. For this issue the functionality is working as per the requirement.
