### ISSUE TITLE
Virtual Network and Subnet options are not present in plugin

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#134]
<b>Environment: </b>Windows/IntelliJ14

The fields for the Cloud service settings is different in story board and different in plug in.
PFB the screen shot in story board.
![storyboard4](https://cloud.githubusercontent.com/assets/10046647/5996327/3bba6140-aacd-11e4-9622-de688bf9e4f8.png)
PFB the screen shot in plugin.
![plugin4](https://cloud.githubusercontent.com/assets/10046647/5996333/4c8a6c18-aacd-11e4-90f3-5b9fda1824f1.png)

**Comment by BeatriceOltean** [comment]
Need to add this in the Java SDK

**Comment by leotilli** [comment]
Duplicate #130
