### ISSUE TITLE
Plugin not showing proper error message when the user writes the name of any existing Cloud service name

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#135]
<b>Environment: </b>Windows/IntelliJ14

In azure portal if the user writes any existing VM name while creating a new VM, it shows error message while creating the cloud service.
PFB the screen shot.
![portal13](https://cloud.githubusercontent.com/assets/10046647/5996390/d23835f6-aace-11e4-9aad-d1122d4182e4.png)

In plugin follow the below steps.
Select 'Create New VM'.
Give details.
Select 'Create New Cloud Service'.
Give an existing Cloud Service name.
Click Create.It will show an error message window as below.
PFB the screen shot.
![duplicatecloud](https://cloud.githubusercontent.com/assets/10046647/5997812/22bf3dbe-aae6-11e4-9df4-1e6cb1c82d55.png)

**Comment by leotilli** [comment]
Improve error message to suggest advanced info.

**Comment by kasturiswain** [comment]
This is reproducible in the latest build.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
