### ISSUE TITLE
Signed in Subscription id is not shown in plugin

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#137]
<b>Environment: </b>Windows/IntelliJ14

As per the story board the plug in should show the signed in id info while creating the VM.
PFB the screen shot.
![storyboardsignedinas](https://cloud.githubusercontent.com/assets/10046647/5996507/ebe3e6ec-aad0-11e4-8d66-8e2ab8a502c7.png)
The Plugin is not able to show the signed in id.
PFB the screen shot.
![pluginsignin](https://cloud.githubusercontent.com/assets/10046647/5996519/0ed49e26-aad1-11e4-80d0-32423e8b8e71.png)

**Comment by BeatriceOltean** [comment]
This user info will show only when log in as user AAD credentials

**Comment by kasturiswain** [comment]
In the latest build plugin  is not able to show the user info even if he has logged in through AD authentication.

**Comment by BeatriceOltean** [comment]
Will be displayed only when the user uses the AAD to sign.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
![sign](https://cloud.githubusercontent.com/assets/10046647/6892491/2d3e58b0-d6e2-11e4-9345-9b25193a9048.png)
