### ISSUE TITLE
On line policy statement not present in any window in plugin

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#139]
<b>Environment: </b>Windows/IntelliJ14

In the Story board we could see that On line Policy Statement link should be present in all of the windows for creating the VM.
PFB the screen shot.
![storyboard2](https://cloud.githubusercontent.com/assets/10046647/5997010/0848014c-aadb-11e4-9519-bd08b93404da.png)

In the story board none of the window have the link for on line policy statement.
PFB the screen shot.
![plugin13](https://cloud.githubusercontent.com/assets/10046647/5997011/0ea141d4-aadb-11e4-9909-21bf114e416c.png)

**Comment by leotilli** [comment]
If we implement a custom wizard (based on the current one), we might be able to address it together with issues #123 and #183
