### ISSUE TITLE
Use Gradle dependencies for Azure Services

### ISSUE THREAD

**Issue by leotilli** [MSOpenTech/msopentech-tools-for-intellij#14]
Whenever Mobile Services and Notification Hubs SDKs get published as Gradle dependencies, we could start adding them through the built in template functionality, and remove the forced Gradle Sync from the end of the wizard, as in PR https://github.com/MSOpenTech/msopentech-tools-for-intellij/pull/10

**Comment by BeatriceOltean** [comment]
Let's close this one for Mobile Services and open a different one for Notification

**Comment by leotilli** [comment]
Created issue #166
