### ISSUE TITLE
plugin not refreshing the Azure activity (mobile service and virtual machine) when user sign in or sign out 

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#140]
<b>Environment: </b>Windows/IntelliJ14

In the Story board there is no option to open the Import Subscription window while creating the VM.
PFB the screen shot.
![storyboard](https://cloud.githubusercontent.com/assets/10046647/5997050/af8d114a-aadb-11e4-936e-60514e4c79b5.png)
In the plug in there is option to open the Import Subscription window while creating the VM.
PFB the screen shot.
![pluginimportsubscription](https://cloud.githubusercontent.com/assets/10046647/5997062/c50f9074-aadb-11e4-83b8-477157b1a3c7.png)

**Comment by BeatriceOltean** [comment]
I'm fine with this as long as it is working

**Comment by kasturiswain** [comment]
plugin not refreshing the Azure activity (mobile service and virtual machine) when user sign in or sign out from this window.
Steps:
Click on Manage subscription from the azure button.
Sign in the subscription if user has not signed in or Sign out if the user has signed in.
close the window.
Here it auto refreshes the azure activity.

click on create VM.
Click on manage subscriptions button.
Sign in the subscription if user has not signed in or Sign out if the user has signed in.
close the window.
Click on cancel.
Here it does not auto refreshe the azure activity.

**Comment by omendrapandey** [comment]
This issue still exist in plugin version 0.1.240

**Comment by ramkumargtv** [comment]
Service explorer is now refreshing in both cases as mentioned in above  cases for <b>plugin version 0.1.302
