### ISSUE TITLE
Plugin creating same cloud service name more than once

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#143]
Plugin allowing same cloud service name more than once.
PFB the screen shot.
![duplicatecloud1](https://cloud.githubusercontent.com/assets/10046647/5997977/097cd08a-aae8-11e4-8a49-d29885c6c6f6.png)

**Comment by BeatriceOltean** [comment]
I repro this issue:
1. select new cloud service
2. created a cloud service that exist 
3. You get the error -EXPECTED
4. The cloud service is added in the drop down for my subscription - NOT EXPECTED

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
