### ISSUE TITLE
Plugin throwing exception while trying to create more than 20 cloud services

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#144]
<b>Environment: </b>Windows/IntelliJ14

Plugin throwing exception while trying to create more than 20 cloud services.
PFB the screen shot.
![morethan20](https://cloud.githubusercontent.com/assets/10046647/5998088/64f023c6-aae9-11e4-9755-54bf474097d7.png)

**Comment by avranju** [comment]
This is by design. Azure enforces resource limits. Current behavior is acceptable.

**Comment by BeatriceOltean** [comment]
The error message is clear. We could only improve the err message with "Please select the advanced info for further details"

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
