### ISSUE TITLE
Plugin throwing exception while creating duplicate storage account

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#145]
Plugin is throwing exception while creating duplicate storage account.
PFB the screen shot.
![storageaccount](https://cloud.githubusercontent.com/assets/10046647/5998261/5fa29118-aaeb-11e4-8700-dabf730aeeca.png)

**Comment by avranju** [comment]
Isn't this how it should be? What's the bug?

**Comment by kasturiswain** [comment]
If the user clicks on "Show advanced info", he will be able to get the proper error message.
