### ISSUE TITLE
Replace "mytenant" with actual tenant name when generating O365 code

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#148]
In PR https://github.com/MSOpenTech/msopentech-tools-for-intellij/pull/113 it was noticed that the tooling generates URLs as string resources in the Android app where the O365 tenant name is hard coded as "mytenant" which is meant to be a placeholder. This needs to be changed so that the actual tenant name is used instead.

**Comment by leotilli** [comment]
Duplicate #114
