### ISSUE TITLE
IntelliJ IDEA New Project image present in Android Studio Create VM windows

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#156]
<b>Environment: </b>Windows/Android Studio 1.0.1

IntelliJ IDEA New Project icon is present in Android Studio Create VM windows.
PFB the screen shot.
![as](https://cloud.githubusercontent.com/assets/10046647/6036078/63ee32ce-ac65-11e4-8528-b70b4ec684af.png)

**Comment by babumuralidharan** [comment]
LGTM.

**Comment by kasturiswain** [comment]
This issue is fixed.
