### ISSUE TITLE
Refresh button should be disabled once it is clicked and azure has not completed the update

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#158]
<b>Environment: </b>Windows/IntelliJ14

Sign the Subscription.
Right Click on Azure button.
Click 'Refresh'.
Again right click on Azure button.
Click 'Refresh'. Here the user should not be able to click on refresh until azure updates the mobile service and VMs.

And also when the refresh button is clicked in Virtual Machines or Mobile Services button, the plugin should not allow the user to click on refresh button in azure button.

PFB the screen shot.
![pluginrefresh](https://cloud.githubusercontent.com/assets/10046647/6036896/8ba8bf7a-ac72-11e4-8698-2f68d66a380b.png)

**Comment by babumuralidharan** [comment]
Another issue related to this one is when user tries to shutdown a VM the status icon needs to change. Currently even after shutting down a VM and refreshing the VM the status icon do not change from running to stopped state which seems to be corrected.

**Comment by kasturiswain** [comment]
This issue is fixed and the functionality is working as expected in the latest build.
