### ISSUE TITLE
Next Button is disabled when no End point selected while creating VM

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#159]
<b>Environment: </b>Windows/IntelliJ14

In azure portal when the user trying to create a new VM and does not give any end point details,
portal is able to create the VM with no end points.
PFB the screen shot.
![portal1](https://cloud.githubusercontent.com/assets/10046647/6037819/8afb3854-ac7d-11e4-8ae7-a8941dabad59.png)
![prtal3](https://cloud.githubusercontent.com/assets/10046647/6037823/90c4cd04-ac7d-11e4-9227-c3e2c40b0e16.png)

In azure plugin when the user trying to create a new VM and does not give any end point details,
The next button is disabled in this case.
PFB the screen shot.
![plugin2](https://cloud.githubusercontent.com/assets/10046647/6037833/b0b376ce-ac7d-11e4-90df-0a78b30c790a.png)

**Comment by kasturiswain** [comment]
This issue is still reproducible in the latest build.

**Comment by akrakovsky** [comment]
Please retest with latest version

**Comment by kasturiswain** [comment]
Tested with the latest version and the issue is reproducible.

**Comment by akrakovsky** [comment]
I tested it with the latest version in Android Studio, and I can see the finish button enabled if there are no endpoints:

![endpoint screenshot](https://cloud.githubusercontent.com/assets/989609/6080112/9dd15c68-adec-11e4-9133-b661bf3f2880.png)

**Comment by kasturiswain** [comment]
I am not able to reproduce the issue.
