### ISSUE TITLE
Plugin error when Android studio version gets updated to newer version 

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#16]
When user updates AS from 0.8.14 -> 0.9.3 (canary channel) it complained about the “unexpected” plugin and forces user to delete it – screenshot below.

This was a change in 0.8.14, when they forced user to move the SDK out of the AS folder. The patch process now validates that the contents of the AS folder haven’t changed since the last update. See these release notes, particularly this:

![image](https://cloud.githubusercontent.com/assets/1501823/5054926/4db847c8-6c10-11e4-9ce6-90c4c69771d4.png)

Same scenario applies for 0.8.9 to 0.8.10

@selvamohandoss,@bharathrajvm, have you guys noticed this ??

**Comment by BeatriceOltean** [comment]
Same as template issue #27

**Comment by babumuralidharan** [comment]
LGTM
