### ISSUE TITLE
Plugin not showing proper error message when a cloud service which is not empty  is selected while creating VM 

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#160]
<b>Environment: </b>Windows/IntelliJ14

In portal if we give a non empty cloud we get a proper error message.
PFB the screen shot.
![portalerr](https://cloud.githubusercontent.com/assets/10046647/6038270/84aea8ec-ac81-11e4-9fb4-203123c9456b.png)

In plugin if we give a non empty cloud its not showing any proper error message.
PFB the screen shot.
![pluginerr](https://cloud.githubusercontent.com/assets/10046647/6038259/779480dc-ac81-11e4-99ec-4f0ff5a5ee28.png)

**Comment by BeatriceOltean** [comment]
In the latest build any cloud service is filtered if it does not have roles

**Comment by kasturiswain** [comment]
This functionality is working as expected.
