### ISSUE TITLE
Plugin throwing exception when existing end point port number is selected while creating VM

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#162]
<b>Environment: </b>Windows/IntelliJ14

Plugin is throwing error message when existing end point is selected while creating VM.
PFB the screen shot.
![plugin61 1](https://cloud.githubusercontent.com/assets/10046647/6039224/9bb17ab6-ac8a-11e4-9bcc-6f36b6a15c7e.png)

**Comment by leotilli** [comment]
Improve error message to suggest advanced info.

**Comment by kasturiswain** [comment]
This issue is reproducible in the latest build.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
