### ISSUE TITLE
Download RDP option is available in plugin when the Remote Desktop port number is not default

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#163]
<b>Environment: </b>Windows/IntelliJ14

In portal if the Remote desktop port is not 3389, Connect option is not enabled.
PFB the screen shot.
![downloadrdperrorportal](https://cloud.githubusercontent.com/assets/10046647/6040083/f8c3252a-ac93-11e4-9eeb-b6584824bc5b.png)

In plugin if the Remote desktop port is not 3389, Connect Remote Desktop option is enabled and it is throwing exception.
PFB the screen shot.
![downloadrdperror](https://cloud.githubusercontent.com/assets/10046647/6040108/3aaf1656-ac94-11e4-980c-8d63c3c7966f.png)

**Comment by babumuralidharan** [comment]
Also this option will not make sense if user is in Mac/Linux. So generating rdp file will only make sense if user is in windows.

**Comment by kasturiswain** [comment]
This issue is fixed and the functionality is working as expected in the latest build.
