### ISSUE TITLE
Library Issues

### ISSUE THREAD

**Issue by BeatriceOltean** [MSOpenTech/msopentech-tools-for-intellij#167]
Library Issues
If you look at the libs folder after adding the Azure Services Activity, you end up with multiples of the same library (javadocs, sources, etc) as well as different versions:
 
![libraryissue](https://cloud.githubusercontent.com/assets/926089/6051197/cc745b74-ac7a-11e4-969f-abba2de960e2.png)

This causes the app to not run due to duplicate dex classes found.

**Comment by leotilli** [comment]
This has already been addressed. We are currently adding just notifications-1.0.1.jar and notification-hubs-0.4.jar , without sources (nor javadoc) that would generate a duplicate dex class compile error.

**Comment by kasturiswain** [comment]
In the latest build in the notification-hubs-0.4.jar is getting added in the latest build.
![167](https://cloud.githubusercontent.com/assets/10046647/6075444/6d1110b2-adf8-11e4-98b8-268f793f9825.png)

**Comment by leotilli** [comment]
This is the expected behavior. Sources (and docs) are no longer added, that are the ones that conflicted with the main library.
