### ISSUE TITLE
Pre-populate Notification Hub parameters in new Azure activity wizard

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#171]
While the wizard for adding a new Azure Services Activity can pull your information for the Mobile Service, you’re still required to enter the information for your Hub manually. Consider pre-populating the fields automatically.

**Comment by BeatriceOltean** [comment]
This is a dupe of 73rd and we have to further discuss with the Notification team regarding the Enhanced Push
