### ISSUE TITLE
Missing image in the getting started guide

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#172]
The [getting started](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/docs/Get%20Started%20MSOpenTechTools%20For%20Android.md) guide has a missing image.

> ![image](https://cloud.githubusercontent.com/assets/628128/6052739/5fc15494-ac8b-11e4-9eb9-eba2334c6727.png)

**Comment by BeatriceOltean** [comment]
Fixed
