### ISSUE TITLE
Remove "Android" as a search keyword from installation instructions

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#174]
When searching for the plugin to install the [instructions](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/docs/Get%20Started%20MSOpenTechTools%20For%20Android.md) say search for “MSOpenTech or Android or Azure”.  Consider taking out “Android” as that leads to a lengthy list of plugin options (including the MSOpenTech one).

**Comment by BeatriceOltean** [comment]
This was fixed
