### ISSUE TITLE
Re-position permission tags in the manifest for Azure services activity

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#175]
Adding the Azure Services Activity adds permissions to the bottom of the manifest file.  I think the common practice is to have permissions above the **application** node in the manifest so we should move those up.

**Comment by leotilli** [comment]
Fixed on Jan 20th (8cfbd72)

And merged on Jan 28th (#113)

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
