### ISSUE TITLE
Next Button should be the default button in the windows when the user enters data in the window

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#183]
<b>Environment: </b>Windows/IntelliJ14

Steps:
Click on Create VM.
Login the subscription.
Click Next.
In the Select Image window default Image type and window name ll be selected.
So Next button should be the default button.But in this case cancel button is the default button.
PFB the screen shot.
![defaubtb1](https://cloud.githubusercontent.com/assets/10046647/6103433/5c2dbeca-b06a-11e4-9e51-d9c469d8d8cf.png)
Give the VM details.
So Next button should be the default button.But in this case cancel button is the default button.
PFB the screen shot.
![defaubtb2](https://cloud.githubusercontent.com/assets/10046647/6103491/efbb238a-b06a-11e4-954c-3f3c213e8580.png)
Select the cloud service.
select the storage account.
So Next button should be the default button.But in this case cancel button is the default button.
PFB the screen shot.
![defaubtb3](https://cloud.githubusercontent.com/assets/10046647/6103507/1d3bc378-b06b-11e4-9097-e1049c5aecd0.png)

**Comment by leotilli** [comment]
If we implement a custom wizard (based on the current one), we might be able to address it together with issues #123 and #139

**Comment by omendrapandey** [comment]
This issue still exist in plugin version <b>0.1.242
