### ISSUE TITLE
Gradle Build error due to duplicate mobile services jar file 

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#19]
__Environment__: Mac/IntelliJ14

Frequency of Repro :  __Intermittent__

* Create new project
* Enable MobileServices and notification hubs
* Sign
* Choose mobile service
* Set the notification details
* Click finish
* Gradle build error on duplicate mobile services jar. 

![screen shot 2014-11-14 at 4 19 06 pm](https://cloud.githubusercontent.com/assets/1501823/5055952/f8fb46ce-6c21-11e4-960f-3cece9528c21.png)

**Comment by kasturiswain** [comment]
This issue is reproducible with latest build.
![gradlebuild](https://cloud.githubusercontent.com/assets/10046647/5933649/7b1ef1a8-a6e9-11e4-95b6-907e908e19a1.png)

**Comment by kasturiswain** [comment]
This is working as expected in the latest build.
