### ISSUE TITLE
Replace "Server Explorer" with "Services Explorer"

### ISSUE THREAD

**Issue by BeatriceOltean** [MSOpenTech/msopentech-tools-for-intellij#191]
This seems a regression.

**Comment by BeatriceOltean** [comment]
![service explorer](https://cloud.githubusercontent.com/assets/926089/6159631/0962b200-b20d-11e4-8a40-5304f9fd0b7d.jpg)

**Comment by avranju** [comment]
Fixed in the private repo! :) Next build should have the correct string.

**Comment by kasturiswain** [comment]
In the latest build it is showing as 'Service Explorer' not  'Services Explorer'.
![serviceexp](https://cloud.githubusercontent.com/assets/10046647/6162362/7bd30b92-b2a7-11e4-93ee-41546cf351da.png)

**Comment by babumuralidharan** [comment]
LGTM in the latest build
