### ISSUE TITLE
Signout should cancel existing service explorer load operation

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#196]
User signs in and the respective mobileservices and virtual machines gets loaded in service explorer. 

While loading the virtual machines if user signs out then existing virtual machine load operation should also be cancelled.

**Comment by omendrapandey** [comment]
This issue still exist in plugin version <b>0.1.240

**Comment by ramkumargtv** [comment]
This issue still exist , Services are still loading even after subscription has been logged out .
But it is not a major issue as you cannot access those services or VM or Storage containers until manage subscription dialog box is open and if we close the dialog box it will unload the Vm , Storage container , etc .
