### ISSUE TITLE
Manage subscriptions dialog gets stuck in a message box loop if there's no OpenSSL and you try to import a subscription

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#202]
The _Manage Subscriptions_ dialog gets stuck in a message box loop if there's no OpenSSL and you try to import a subscription. Here're the steps to reproduce this with a fresh install of the plugin on a system that does not have OpenSSL installed and configured. This issue was reported by @DonGlo.
1. Right click on the **Azure** node in services explorer.
2. Choose _Manage Subscriptions_.
3. Click the "Import Subscription" button.
4. Pick a subscription settings file.
5. Click the "Import" button.
6. A message pops up stating that you need to configure OpenSSL and provide the path the OpenSSL binary. Cancel out of this dialog.

Now there's no way to exit the _Manage Subscriptions_ dialog without signing in or importing a subscription settings file unless you terminate the IDE process.

**Comment by babumuralidharan** [comment]
Yes this is an issue and i was able to repro with the above steps.

**Comment by BeatriceOltean** [comment]
Hi Kasturi, would you please check if this bug is still active?

**Comment by kasturiswain** [comment]
Yes this issue is reproducible.
IDE is showing the below exception when the user trying to cancel the dialog.
![openssl](https://cloud.githubusercontent.com/assets/10046647/6774999/6b4fb76c-d150-11e4-82c3-9bf9c26c2f5a.png)

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
