### ISSUE TITLE
Newly Created Mobile Services are accessible only after considerable interval of time

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#203]
Right click mobile service -> Create Table -> specify the table name and click create gives exception. This issue was reported by @DonGlo 

![image](https://cloud.githubusercontent.com/assets/1501823/6275596/4c49341c-b835-11e4-9f25-9fd12f1b72f1.png)

**Comment by babumuralidharan** [comment]
This is something temporary i guess. This was working fine before. May be API flakiness??

**Comment by DonGlo** [comment]
I can replicate this every time on my machine.

**Comment by kasturiswain** [comment]
This issue is reproducible when the user creates a new mobile service from the plug in and tries to  create table/API/new job in the created mobile service.

**Comment by BeatriceOltean** [comment]
Refresh will allow to operate, it is dependent of the provisioning time. This is a low bug.

**Comment by akrakovsky** [comment]
We need to research if there is a way of querying the status of the mobile service.

**Comment by avranju** [comment]
Let's check with the mobile services team as to what would be a reliable way to get status of readiness of a newly created mobile service.

**Comment by ramkumargtv** [comment]
The issue still exist for newly created mobile services , and after considerable amount of times one can create table , jobs and API's .

**Comment by martinsawicki** [comment]
deprecated functionality
