### ISSUE TITLE
Plugin should not enable the start button while VM creation provision is in progress

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#213]
<b>Environment: </b>Windows/IntelliJ14
In the portal when VM creation is in progress start button is disabled.
![portal](https://cloud.githubusercontent.com/assets/10046647/6457445/e9d1e4e4-c19b-11e4-9d62-c7dc13648bc4.png)

In the plugin when VM creation is in progress start button is enabled.
![plugin](https://cloud.githubusercontent.com/assets/10046647/6457455/fea4e0a6-c19b-11e4-8c57-90cc6ea10ec8.png)

**Comment by BeatriceOltean** [comment]
If we know from the API if the VM is provisioning then we can disable the Start in the menu.

**Comment by leotilli** [comment]
Should we follow Visual Studio behavior that allows to operate as if it's already started, while in fact it is still provisioning

![image](https://cloud.githubusercontent.com/assets/1890830/6830798/f546331e-d2fa-11e4-9ad7-4279b9c15f27.png)

Or should we mimic the Portal's behavior

![image](https://cloud.githubusercontent.com/assets/1890830/6830812/164e848a-d2fb-11e4-8e6b-56993c27d718.png)

**Comment by BeatriceOltean** [comment]
The portal behavior is more accurate.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
