### ISSUE TITLE
Plugin throwing exception when user trying to do any activity on the newly created VM if the cloud services was deleted from the portal

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#214]
Plugin throwing exception when user trying to do any activity on the newly created VM (provisioning is in progress) and the corresponding cloud service is deleted from the portal.
![refresh](https://cloud.githubusercontent.com/assets/10046647/6457886/8ba8640e-c1a2-11e4-9404-44e24f825b95.png)

**Comment by BeatriceOltean** [comment]
The exception shows the current status of the VM. The VM is deleted so it is either in the invalid state either does not exist. The error message is relevant.
