### ISSUE TITLE
Prompt Window title should be different for different VM activity(Start/Shut down/Restart/Delete)

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#218]
<b>Environment: </b>Windows/IntelliJ14

For any VM activity(Start/Shut down/Restart/Delete) it Prompts a window which is asking for user confirmation.
In all the above cases the window title is same (“Service explorer”). 
Should not we have different window title for different activity?

**Comment by BeatriceOltean** [comment]
We can go with generic title "Service Explorer" for all the confirmation dialogs.

**Comment by kasturiswain** [comment]
If the requirement is to have same title for different window the requirement is working as expected.
