### ISSUE TITLE
Plugin throwing exception when user trying to create more than one scheduled JOB

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#220]
<b>Environment: </b>Windows/IntelliJ14
When the  user trying to create more than one scheduled JOB In the portal, it is showing the error message as below.
![portalschedule](https://cloud.githubusercontent.com/assets/10046647/6554931/c55391cc-c686-11e4-91b5-933f813e6257.png)

When the  user trying to create more than one scheduled JOB In the Plugin it is throwing exception as below.
![pluginschedule](https://cloud.githubusercontent.com/assets/10046647/6554937/e133f134-c686-11e4-9337-e7a8a57b79d8.png)

**Comment by kasturiswain** [comment]
This issue is fixed in the latest build and functionality working as expected.

**Comment by kasturiswain** [comment]
Plug in throwing the below exception in the latest build for the above.
![duplicatejob](https://cloud.githubusercontent.com/assets/10046647/7083453/96bc1d40-df7f-11e4-817c-c7ce895d5098.png)

**Comment by BeatriceOltean** [comment]
For regression

**Comment by omendrapandey** [comment]
Plugin able to create more than one scheduler now .
