### ISSUE TITLE
Create mobile service returning Exceeded quota error when no servers exist

### ISSUE THREAD

**Issue by DonGlo** [MSOpenTech/msopentech-tools-for-intellij#221]
I tried to create a mobile service an "Error creating the service" dialog. Showing advanced info shows the error to be:
Cannot move or create server. Subscription '789bd9c7-7b03-463c-8a54-74a6ad134e35' will exceed server quota.

I currently have no Mobile services or SQL databases in the subscription. 

![2015-03-09_10-17-29](https://cloud.githubusercontent.com/assets/9483877/6560393/f6ab1d34-c646-11e4-803a-723885a056e2.jpg)

**Comment by BeatriceOltean** [comment]
This maybe an issue with creation of the free DB. The mobile service cannot be created without the free DB. Is the subscription shared among multiple users? 

If you can create it from the portal and you do not get the exception then the bug is in the plugin.

**Comment by DonGlo** [comment]
Ok, Now I understand what is going on. The dialog says create a database.

Under the covers it is creating a NEW server to put it on even if you have existing servers that have 
![2015-03-20_12-44-14](https://cloud.githubusercontent.com/assets/9483877/6759782/12a44ddc-cf00-11e4-9dc6-70cb46d5ad7e.jpg)
no databases on them. 
There is a disconnect between the UI dialog and the error that is generated. 
So, I had 5 servers that  had been created when I ran the tool on previous occasions.  I deleted the mobile service and the databases each time, but the servers were not deleted at that time.
Then came the point that I had 5 servers left over, and NO databases. Servers don’t show until you dig down in the Azure UI.
There needs to be a better statement in the UI as to what is happening and/or error returned so that is clearer what the issue is.

**Comment by leotilli** [comment]
The same behavior happens in VS.

![image](https://cloud.githubusercontent.com/assets/1890830/7321076/853a178c-ea76-11e4-92ec-06e3e2b56a78.png)

 We'll be changing the popup message to suggest reading the advanced info.

**Comment by DonGlo** [comment]
Do we have enough info to do better than that? I would argue that we are potentially dealing with an audience that that is not as familiar with the Microsoft ecosystem. If we have definitive error information we can provide, is there are reason not to do so?

**Comment by BeatriceOltean** [comment]
There is no metadata in the XML that we receive from Azure VM API.
