### ISSUE TITLE
User should have an option to create vm from custom image through plugin

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#222]
When the user creates a new VM through plugin, he should have an option to create vm from custom image.

**Comment by leotilli** [comment]
Showing custom images under Private|VM Images

![image](https://cloud.githubusercontent.com/assets/1890830/7327042/6c154612-eaa0-11e4-8be9-dd1024fea38b.png)

**Comment by kasturiswain** [comment]
Plugin Showing custom images under Private|VM Images.
