### ISSUE TITLE
Plugin is not able to create a new Storage Account

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#231]
<b>Environment: </b>Windows/IntelliJ14

Steps:
Sign in Subscription.
Click Azure.
Right Click storage.
Click Create Storage Account.
Give the details.
Select Create.
Plugin not able to create the storage, it is just showing the progress bar.
PFB the screen shot.
![createstorage](https://cloud.githubusercontent.com/assets/10046647/6750099/fa9261e4-cf1c-11e4-903c-cc4300f67006.png)

**Comment by kasturiswain** [comment]
After closing the window "create storage account" it is showing null pointer exception as below.
![null1](https://cloud.githubusercontent.com/assets/10046647/6775594/64422cee-d159-11e4-876a-eea7a6135d53.png)

**Comment by leotilli** [comment]
I was unable to reproduce this issue with the latest version, following the mentioned steps. Could you please validate if it's still happening?

**Comment by kasturiswain** [comment]
I am able to create a new Storage account in the latest build.
But the created storage account is not shown to the user in the storage tree after user clicks the "create" storage button. 
The user has to click the refresh button of the storage, then only the latest created storage is shown to the user.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
