### ISSUE TITLE
Plugin should have a scroll bar at the bottom when showing the blob files in the window

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#236]
<b>Environment: Windows/IntelliJ14</b>

Steps:
Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
expand  'Blobs'.
Select a particular blob. This window should have a scroll bar below so that the user will be able to see all the data clearly.
PFB the screen shot.
![scrollbar](https://cloud.githubusercontent.com/assets/10046647/6750797/3edbfd4a-cf24-11e4-872d-91a71f73a2e6.png)

**Comment by akrakovsky** [comment]
Having resizable columns, I wouldn't allow scrolling horizontally. 

Relevant data should be visible anyway (the URL, which is the longest data in the grid, is obtained by the option "Copy URL")

**Comment by kasturiswain** [comment]
As per the above requirement, the functionality is working as expected.
