### ISSUE TITLE
Attach External Storage option is not available in Plugin in Storage

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#237]
<b>Environment: </b>Windows/IntelliJ14

In the Story board Attach External Storage option is available.
In the Plugin Attach External Storage option is not available.

**Comment by akrakovsky** [comment]
We are checking viability. This feature could be added on later releases.

**Comment by omendrapandey** [comment]
Attach External Storage option is now available for the storage .
