### ISSUE TITLE
Helper class methods are added into  Azure Service activity class if the user cancels  the Add Options

### ISSUE THREAD

**Issue by selvamohandoss** [MSOpenTech/msopentech-tools-for-intellij#24]
<b> Environment </b> : Intellij14
<b> Repo </b>
1) Create Azure Service Activity by selecting  the option Azure Mobile service and Notification Hub.
2) Click on Finish
3) It loads Add Mobile Service Wizard
4) Select  any  of the available Mobile Service
5) Click on Next and Set the Valid Values on SenderID,Connection String,Hub name.
6) Click on <b> Cancel </b>

<b> Actual </b>
 Windows Azure Mobile Service Client libraries are not added into the project .But it adds the Client instantiate code on Azure Service  Activity Class
 MobileServiceClient mobileServiceClient = MobileService.getInstance(this);

<b> Expected </b> If the User  clicks on Cancel Button on Add Microsoft Service Wizard,it should not add helper class code on AzureService Activity Class

**Comment by omendrapandey** [comment]
This issue is still not fixed , it is still adding client instantiation code 

 MobileServiceClient mobileServiceClient = getMobileServiceClient(this);

to the azure service activity class .

**Comment by kasturiswain** [comment]
Not able to test as plug in throwing exception while configuring the Notification Hub.
Will test it once issue #341.

**Comment by kasturiswain** [comment]
This issue is reproducible in the build 0.1.235.and 0.1.36 build.

**Comment by martinsawicki** [comment]
obsolete
