### ISSUE TITLE
Refresh Blob file option is not present in plugin

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#240]
<b>Environment: </b>Windows/IntelliJ14

Steps:
Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand Blobs.
Select a blob container.
Select a blob.

In story board we have the following activity options.
![storyboardoption](https://cloud.githubusercontent.com/assets/10046647/6751366/20301e26-cf29-11e4-9c72-9ecc7e7547c3.png)

In plugin we have the following activity options.
![pluinoption](https://cloud.githubusercontent.com/assets/10046647/6751375/300c9b3a-cf29-11e4-8d93-474473f1ce2f.png)

**Comment by akrakovsky** [comment]
I checked and there is no option for refreshing singular files in Visual Studio. Besides, what purpose would have refreshing singular files on the blob container?

**Comment by kasturiswain** [comment]
Yes, there is no meaning of refreshing singular files on the blob container.
But as it was written in the story board, I logged it.
Thanks for your input.
