### ISSUE TITLE
User not able to do any activity in the blob file by right clicking the file property when he changes the sequence of the file properties

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#243]
<b>Environment: </b>Windows/IntelliJ14

Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand Blobs.
Select a blob container.
Select a blob.
Change the Sequence of the fields.(Like exchange Size and name)
Right Click on file name.
It will not allow the user to do any activity.
PFB the screen shot.
![sequence](https://cloud.githubusercontent.com/assets/10046647/6777441/c3c5ad1a-d16f-11e4-9a27-96dc3e5f63cb.png)

**Comment by akrakovsky** [comment]
i think the feature of reordering the columns should be disabled.

**Comment by kasturiswain** [comment]
The feature of reordering the columns is disabled.
This issue is fixed and functionality is working as expected in the latest build.
