### ISSUE TITLE
Plugin allowing the user to do activities for already opened blob file even after clearing the subscription

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#247]
<b>Environment: </b>Windows/IntelliJ14
Steps:
Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand Blobs.
Select a particular blob file.
Now clear the subscription.
Right Click on one Blob file.
It will allow the user to do the activities.

**Comment by BeatriceOltean** [comment]
Requires refactoring. Decided to be done after Elena's PR.

**Comment by omendrapandey** [comment]
This issue still exist in plugin version <b>0.1.242

**Comment by ramkumargtv** [comment]
This issue is fixed in <b>plugin version 0.1.302</b> as after clearing subscription , all the opened windows get closed .
