### ISSUE TITLE
Plugin throwing exception when user giving existing table name while creating a table

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#261]
<b>Environment: </b>Windows/IntelliJ14
Steps:
Open Services Explorer.
Sign in Subscription.
Open Mobile Services.
Right click on a Mobile Service.
Select Create table.
Give an existing table name.
Plugin throwing the below exception.
![duplicatetable](https://cloud.githubusercontent.com/assets/10046647/7083563/18a8bede-df81-11e4-87e4-6b3091f1d089.png)

**Comment by leotilli** [comment]
I'm getting the table name warning, following the exact same steps, in Windows/IntelliJ 14.1.1
I'm making sure not to load/refresh the mobile service content. I'm right clicking right after opening Mobile Services.

![image](https://cloud.githubusercontent.com/assets/1890830/7262151/c0802afa-e84d-11e4-8016-5591f8a3bab3.png)

**Comment by kasturiswain** [comment]
Not able to reproduce the issue in the latest build.
