### ISSUE TITLE
Toolbar options missing

### ISSUE THREAD

**Issue by iandow** [MSOpenTech/msopentech-tools-for-intellij#263]
I'm not seeing the Azure toolbar options after installing this plugin in Intellij 13.1.4
![See screenshot](https://cloud.githubusercontent.com/assets/1383911/7102193/b23981a8-e02d-11e4-834e-88800e38f275.png)
.

**Comment by BeatriceOltean** [comment]
Hi Ian, do you have  'Toolbar' checkbox checked in Menu View -> Toolbar ?

**Comment by iandow** [comment]
Yes

**Comment by BeatriceOltean** [comment]
Hi Ian, would you please check the latest version 0.1.194?

**Comment by iandow** [comment]
Bingo!  It's working now. Thanks!

![screen shot 2015-05-14 at 9 14 45 pm](https://cloud.githubusercontent.com/assets/1383911/7646835/4aaecb22-fa7e-11e4-94a0-1f8569bf1388.png)
