### ISSUE TITLE
Edit option should allow the user to edit the key values in the table

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#270]
<b>Environment: </b>Windows/IntelliJ14

Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand tables.
Select a particular table.
Add an entity.
Right Click on the entity.
Click on edit.
It should allow the user to edit the key values.
PFB the screen shot.
![edit1](https://cloud.githubusercontent.com/assets/10046647/7317041/c5ba2d9c-ea99-11e4-9bb7-f0f4d3449293.png)

![edit2](https://cloud.githubusercontent.com/assets/10046647/7317045/cd065c88-ea99-11e4-9ba2-28980c89e768.png)

**Comment by akrakovsky** [comment]
This is by design. Visual Studio also doesn't allow editing the partition key and row key of the entity once created.

**Comment by BeatriceOltean** [comment]
By design
