### ISSUE TITLE
Running Query builder for time stamp able to show the result in greater than equals to and less than equals to, but not able to for equals to operation

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#273]
<b>Environment: </b>Windows/IntelliJ14

Sign in Subscription.
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand tables.
Add an entity.
Click Query builder.
Select property name as 'Time Stamp'.
Select operation as 'Equals to'.
Give the value same as time stamp.
Click 'OK'.
Run the Query.
It does not show the particular entity.

**Comment by akrakovsky** [comment]
It is the same value with time included just as date? 

The date picker let you select just the date, and it defaults to 00:00hs. Equals would not match unless the same time is specified.

**Comment by kasturiswain** [comment]
I had change the default time.
PFB the screen shot.
![datetime](https://cloud.githubusercontent.com/assets/10046647/7349565/af244fec-ed17-11e4-9c61-38f7f63315a9.png)

**Comment by akrakovsky** [comment]
The problem here seems to be that milliseconds are not shown on the Timestamp field. If the exact milliseconds of the timestamp are input, there would be a match. 

Visual studio has the exact same problem, I would suggest leaving this behaviour as it is.

**Comment by babumuralidharan** [comment]
@akrakovsky VS might have the same issue but i would recommend this to be solved in our plugin. Can't this be handled in our case ?

**Comment by akrakovsky** [comment]
This is how the current API for tables is working for us and for Visual Studio too. We can't handle it from our side.

**Comment by babumuralidharan** [comment]
If this is a limitation from api let's create an issue to api. Agree this has to be handled at api level if api is not returning us the right timestamp value. Can you log in a issue for this in api repo @akrakovsky ?

**Comment by omendrapandey** [comment]
This issue still exist in plugin version <b>0.1.242

**Comment by ramkumargtv** [comment]
Issue still exist for plugin version 0.1.3012 .
