### ISSUE TITLE
Need delete storage account for storage feature

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#282]
Is there any api limitation that is preventing us to implement this feature ?

**Comment by omendrapandey** [comment]
The delete option for storage account is now there in the new build , it is successfully able to delete storage containers .
But for those storage container which have active images or disk , it is not able to delete them and not showing any status message whether the storage has been deleted or not .
The plugin should throw some error message for these type of storage account like " this storage account could not be deleted as it has active images/disks . "

**Comment by babumuralidharan** [comment]
@omendrapandey i agree we should show some user friendly messages. @akrakovsky we get error message from server side for this scenario right ??

**Comment by omendrapandey** [comment]
Raised issue #342 for problem in deletion of storage account with active images/disk , Deletion of storage account is otherwise working fine .
