### ISSUE TITLE
Append subscription name in Root name Azure similar to VS

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#283]
If user either logins and has one subscription or multiple subscription can we append the subscription name to the root node azure similar to that of VS. Refer screenshot for details. VS on the left and IntelliJ on the right. 

![image](https://cloud.githubusercontent.com/assets/1501823/7505638/bca627f0-f409-11e4-85e1-357c3e039f12.png)

PS : There are themes related issues that i will log seperately.

**Comment by omendrapandey** [comment]
The subscription name is now appended .
