### ISSUE TITLE
Need Delete Mobile Service for Mobile Services feature

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#285]
Currently , to delete the  created mobile service , user need to access the azure portal .
The  delete option should be available with in the plugin for Mobile Service .

P.S. - With in the Mobile Service delete option is missing for Tables , Custom API's and Job's Scheduler .

**Comment by omendrapandey** [comment]
The delete option for mobile service has been added , and it is able to successfully delete the mobile services . 
But delete option for Tables , API and Job Scheduler are still missing from the plugin .

**Comment by martinsawicki** [comment]
functionality deprecated
