### ISSUE TITLE
Invalid account for O365 cause the widget for Office to stuck 

### ISSUE THREAD

**Issue by BeatriceOltean** [MSOpenTech/msopentech-tools-for-intellij#289]
# Repro in IntelliJ 14.1.1: 
1. Log in with MS account (one that does not have access to O365)
2. Choose the New Activity - for Microsoft /Office365 

The widget is trying to load the O365 permissions for the account that does not have permissions and gets stuck. 
![loading o365err](https://cloud.githubusercontent.com/assets/926089/7526462/8c6a2916-f4c6-11e4-906f-32bc2f923cf2.png)
# Expected:

no services in the Message table
instead of Loading and the ability to sign out and sign in with the appropriate account. 
Cancel should not generate an activity or the SDK because we did not yet informed the user about all the components that are added to his project

**Comment by babumuralidharan** [comment]
Refering #276 here.

**Comment by babumuralidharan** [comment]
Now we do not see this error anymore as mentioned in #276

**Comment by omendrapandey** [comment]
Hi @babumuralidharan , the issue is still there , even though No Class def found error is not there as it was in the case of #276 .. the widget will still get stuck if logged on with MS account that doesn't have O 365 access .

**Comment by BeatriceOltean** [comment]
This was fixed. It seemed to be caused by deleting some 3rd party libraries we omitted from the Ant script
