### ISSUE TITLE
Azure Service Activity  added to the project with compilation error .

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#294]
OS - Windows
Plugin Version - 0.1.197
IDE - Intellij Idea Ultimate 14.1.2 , JRE 1.8
Authentication - Publish Settings file

Steps - 
Create an application.
Add a new Azure Service Activity .
They will be added to the project with compilation error.

<pre><code>Information:Gradle: Executing tasks: [:app:assembleDebug]
Information:5/11/2015 11:20 AM - Compilation completed with 2 errors and 0 warnings in 7s 868ms
C:\Users\android\IdeaProjects\MyApplication18\app\src\main\AndroidManifest.xml
Error:(18, 9) Gradle: Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:18:9
Error:(18, 9) Gradle: Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:18:9
>     is also present at com.microsoft.azure:azure-notifications-handler:1.0.1:13:9 value=(@drawable/ic_launcher)
>     Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:16:5 to override</pre></code>
> Snap attached .
> ![complation](https://cloud.githubusercontent.com/assets/12275872/7563867/f67c7df0-f7fe-11e4-8b57-538185ec85bd.png)
> P.S - Commenting out the error giving line in AndroidManifest.xml file  or by following the suggestion as suggested in the error box , the Activity is successfully compiling and activities are successfully added to project .

**Comment by akrakovsky** [comment]
This seems to be an issue with the notifications handler library. They are working on it, we will re-test this once the new version of the library is available.

**Comment by martinsawicki** [comment]
obsolete; support deprecated

**Comment by vivekpatani** [comment]
What does this mean? How to circumvent this issue?

**Comment by OscarCanek** [comment]
Which was the issue resolution?

**Comment by falsevapor** [comment]
This is ridiculous. So you closed the issue just because you just felt like it? Because you needed to show to your bosses that the number of opened tickets is going down? I hope whoever closed this has lost the job.
