### ISSUE TITLE
O 365 Activity class file added to the project even if credentials are not given .

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#295]
OS - Windows
Plugin Version - 0.1.197
IDE - Intellij Idea Ultimate 14.1.2 , JRE 1.8
Authentication - Publish Settings file

Steps - 
Create an application.
Add a new O 365 activity to the app .
<b>When asked for credentials to Sign in to Microsoft Account .
Don't provide any credentials and just Click the Close button of the wizard .
![activity](https://cloud.githubusercontent.com/assets/12275872/7587701/e93db8b6-f8d5-11e4-9408-60f7146e6226.png)

It is still adding the "O 365 Activity.java "  file to the project .
</b>

**Comment by BeatriceOltean** [comment]
Let's focus on not having the activity file for now. I will open a new issue for the gradle dependencies.

**Comment by kasturiswain** [comment]
Without giving O365 credentials plugin not allowing to add O365 activity.
