### ISSUE TITLE
Dropdown icon disappears when database are loaded while creating Mobile Services - UI Issue

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#297]
OS - Ubuntu 12.04 
Plugin Version - 0.1.201
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.8
Authentication - Publish Settings file

Steps - 
Create a new Mobile Service .
It will open a dialog box with a drop down icon for database .
![fss](https://cloud.githubusercontent.com/assets/12275872/7653589/906d74cc-fb34-11e4-9598-97d19659540a.png)
<b>But after the database are loaded , the dropdown icon disappears</b>
![sd](https://cloud.githubusercontent.com/assets/12275872/7653609/ad218374-fb34-11e4-8b45-2315e93d209e.png)

P.S. - This issue is not reproducible on Windows .

**Comment by omendrapandey** [comment]
This issue still exist in plugin version 0.1.240

**Comment by ramkumargtv** [comment]
Issue is fixed in plugin version 0.1.302
