### ISSUE TITLE
Adding subscription through sign in methods pop up 3 SignIn box in Ubuntu 

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#299]
OS - Ubuntu 14.04
Plugin Version - 0.1.204
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.7
Authentication - Sign In

Steps - 
Right Click Azure 
Click Manage Subscriptions
Click Sign In button
Provide credentials details
Click Close button.

<b>It pops up 3 SigIn Dialog box , which again ask for MS account credentials .
One SignIn box activates one services at a time , i.e. One Sign In Box will starts the mobile service , other will start Virtual machine and  one box will start the storage account .</b>
![image](https://cloud.githubusercontent.com/assets/12275872/7681030/d630ca16-fd89-11e4-848c-3fd4454947be.png)

**Comment by babumuralidharan** [comment]
This is a known issue. Not a blocking one. Closing this issue.
