### ISSUE TITLE
Right click selection of  row in storage table is not working

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#302]
OS - Windows
Plugin Version - 0.1.205
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.8
Authentication - Publish Settings file

Steps:
Click Azure.
Click storage.
Expand a Storage Account.
Expand a particular Storage.
Expand tables.
Expand a particular table.
Add few entities to the table.

<b>Bring the cursor to any row and right click the mouse button.
It will have edit and delete option for the row , which are not responding .

These option are responding when row selection is done through left click of the mouse ,whereas ,  In VS both right and left click are able to select the row . </b>
![untitled](https://cloud.githubusercontent.com/assets/12275872/7702284/97f2fc10-fe4c-11e4-82e0-1534eba65467.png)

**Comment by BeatriceOltean** [comment]
This may be fixed after the empty rows was fixed and the row is selected. Please regress

**Comment by omendrapandey** [comment]
Hi @BeatriceOltean , the empty row problem has been fixed , but this problem still exists .
Row selection is still not happening through right click in storage table .

**Comment by omendrapandey** [comment]
Right Click selection is now working fine ..
