### ISSUE TITLE
Buttons can't be viewed while adding activity to the application in android studio

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#311]
OS - Ubuntu 14.04
Plugin Version - 0.1.210
IDE - Android Studio, JRE 1.8
Authentication - Publish Settings file

Steps -
Create an application.
<b>Try to add a new O 365 activity or Azure Activity to the app .
The New Android Activity Wizard is not able to show four button at the bottom right ,i.e. Previous , Next , Cancel and Finish buttons . 
The wizard is also not resizing and thus these buttons can't be viewed .

P.S - Issue specific to Android studio in ubuntu environment only .</b>
![screenshot from 2015-05-25 23 53 08](https://cloud.githubusercontent.com/assets/12275872/7797536/edca3ce4-030a-11e5-843b-40499b2b9a2f.png)

**Comment by akrakovsky** [comment]
This looks like an issue of Android Studio itself. We have no control on how this wizard is shown.

**Comment by ramkumargtv** [comment]
Issue still exist for Android studio in Ubuntu environment .

**Comment by martinsawicki** [comment]
this functionality has been deprecated
