### ISSUE TITLE
Retain SSL for storage endpoint URIs for regions that are outside of China

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#317]
Due to an outstanding SSL certificate issue the plugin converts SSL storage endpoint URLs to plain HTTP URLs. This needs to be scoped so that such replacement occurs only for storage endpoints that are homed in datacenters based out of China as opposed to all datacenters the way it is right now.

**Comment by babumuralidharan** [comment]
@ramkumargtv, can you mark your observations on this issue?

**Comment by ramkumargtv** [comment]
For US subscription, The Storage URL end points contain HTTPS protocol
For Moon Cake Subscription, The Storage URL End point Contains HTTP protocol
