### ISSUE TITLE
Plugin is attaching already existing external storage account

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#325]
<b>Environment: </b>
OS - Windows
Plugin Version - 0.1.221
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.8
Authentication - Publish Settings file

<b>Steps: </b>
Expand Azure.
Right click on Storage.
Click 'Attach External storage account.
Give the details for HTTPS connection.
Click 'ok'.
Attach the Previous Storage Account again in the same procedure.
Visual studio is showing the below error message.
![vs](https://cloud.githubusercontent.com/assets/10046647/7910670/45cba96e-0874-11e5-85c8-af52a82d0794.png)

Intellij Plugin Allowig to attach the same storage account again.
PFB the screen shot.
![intellij](https://cloud.githubusercontent.com/assets/10046647/7910685/650347c4-0874-11e5-9eb7-0a61f595eec4.png)

**Comment by omendrapandey** [comment]
This issue is resolved now .
