### ISSUE TITLE
Plugin throwing Exception when user trying to attach external storage in option "specify custom end points"

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#326]
<b>Environment: </b>
OS - Windows
Plugin Version - 0.1.221
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.8
Authentication - Publish Settings file

<b>Steps: </b>
 Expand Azure.
Right click on Storage.
Click 'Attach External storage account'.
Give the details for the option "specify custom end points".
Click the check box Remember Account Key.
![storagedtl](https://cloud.githubusercontent.com/assets/10046647/7910846/ae52aa54-0875-11e5-8522-7bea9e2a5f05.png)

Click 'ok'.
Select the attached Storage.
It throwing Exception while loading Tables,Queues and Blobs.
![exception](https://cloud.githubusercontent.com/assets/10046647/7910901/15f640bc-0876-11e5-8d93-987b11a61b66.png)

**Comment by omendrapandey** [comment]
This issue is resolved now .
