### ISSUE TITLE
Plugin user should have the option to scale the mobile service to paid scale mode .

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#335]
Plugin Version - 0.1.226

In the current plugin , the mobile services created are by default of free scale mode and there is no option with in the plugin to scale up the mobile service to paid scale mode .

This could cause limitations to the user such as inability to create more than one scheduled jobs .

**Comment by martinsawicki** [comment]
mobile services support in IntelliJ toolkit has been deprecated.
