### ISSUE TITLE
Use Gson as the default JSon ser/de library

### ISSUE THREAD

**Issue by leotilli** [MSOpenTech/msopentech-tools-for-intellij#34]
Address serialization enhancements as mentioned in PR https://github.com/MSOpenTech/msopentech-tools-for-intellij/pull/33 discussion

**Comment by kasturiswain** [comment]
Below are the Json Occurrences.
![gson](https://cloud.githubusercontent.com/assets/10046647/6436812/a1e5e10a-c0db-11e4-8777-be5c1996c0ea.png)

**Comment by leotilli** [comment]
JsonSlurper is no longer being used in the code.
