### ISSUE TITLE
Adding Microsoft activities  to the project option is missing in intellij

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#340]
<b>Environment: </b>
OS - Windows / Ubuntu 14.04
Plugin Version - 0.1.227 , Daily Build 300
IDE - Intellij 14.1.3, JRE 1.8
Authentication - Publish Settings file

<b>Steps</b>
Create a android  project in intellij.
<b>Go to the app folder and right click on it.
Select New .
Microsoft activity option is unavailable in case of intellij .</b>
Screenshot attached for intellij .
![intellij](https://cloud.githubusercontent.com/assets/12275872/8103557/f869754a-1046-11e5-93ef-223f969ba5de.png)
<b>Although , in case of Android Studio , we can still add Microsoft activities as we used to add earlier.

Screenshot for Android Studio attached.
![android](https://cloud.githubusercontent.com/assets/12275872/8103587/3873d086-1047-11e5-9230-f7a03ac92cfa.png)

**Comment by kasturiswain** [comment]
This issue is reproducible in  the build 0.1.235.

**Comment by omendrapandey** [comment]
Issue is not reproducible in build 0.1.239
