### ISSUE TITLE
Plugin not throwing any error message  while trying to delete storage account with leased resources

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#342]
<b>Environment: </b>
OS - Windows
Plugin Version - 0.1.227 , Daily Build 300
IDE - Intellij 14.1.3 , JRE 1.8
Authentication - Publish Settings file

<b>Steps -</b>
Click Azure.
Expand Storage.
Select storage account which has any active resources such as active vm images/disk.
<b>Right Click and Select Delete.

<b>Plugin is not able to delete them and not showing any status message whether the storage has been deleted or not .

The plugin should throw some error message for these type of storage account like " this storage account could not be deleted as it has active images/disks . "  as it was throwing in the case when we are trying to delete the blobs which contains those leased resources .
</b>

**Comment by kasturiswain** [comment]
Detailed Steps :
Create a new Storage Account.
Create a new Virtual Machine. While creating the VM in VM configuration, give the “storage account” name as the created storage account. Create the VM.
Click Azure.
Expand Storage.
Select storage account which has created and which contains the created VM.
Right Click and Select Delete.
Plugin not showing any error message, while in portal it is showing error message as” Storage account testst123245 has some active image(s) and/or disk(s), e.g. deletetestvm11-deletetestvm11-0-201506160740040915. Ensure these image(s) and/or disk(s) are removed before deleting this storage account.”.

**Comment by omendrapandey** [comment]
This issue has been fixed  in build 0.1.239.
