### ISSUE TITLE
Plugin not able to add azure service activity to the project if notification hub is checked

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#343]
<b>Environment:</b>
OS - Ubuntu 14.04 
Plugin Version - 0.1.227 , Daily Build 300
IDE - Android Studio 1.2.1.1 , JRE 1.8
Authentication - Publish Settings file

<b>Steps : </b>
Create a project.
Add an azure service activity to the project.
<b>While adding Azure service activity , Check Notification Hub check box.
Configure the Notification Hub accordingly.
Click Finish.
</b>
The azure service activity will not be added to the project .

**Comment by kasturiswain** [comment]
plug in throwing exception while configuring the Notification Hub(checked) And without configuration, plug in not allowing to add azure service activity which is correct.
