### ISSUE TITLE
IDE not able to resolve symbol while adding azure service activity and thus causing error

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#344]
<b>Environment:
OS - Ubuntu 14.04 
Plugin Version - 0.1.227 , Daily Build 300
IDE - Android Studio 1.2.1.1 , JRE 1.8
Authentication - Publish Settings file

Steps</b>
Create a project.
Add an azure service activity to the project.
While adding Azure service activity , Optionally Check Launcher and Azure Mobile Service Client .
Configure the Azure mobile service client accordingly.
<b>But , do not check notification hub , as it will not add the activity to the project.</b>
Click Finish. 

<b>AzureServiceActivity class file will be added to the project with errors due to unresolved symbol.

![11](https://cloud.githubusercontent.com/assets/12275872/8107387/6fb44188-1066-11e5-876c-c56f12779342.png)

![12](https://cloud.githubusercontent.com/assets/12275872/8107396/78ce647e-1066-11e5-93ee-3329d532543b.png)

**Comment by kasturiswain** [comment]
Not able to repro in the latest build.
