### ISSUE TITLE
Plugin throwing exception while loading Mobile services, virtual machines and storage when keep me signed  in check box is not selected

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#350]
<b>Environment:</b> 
OS - Windows
Plugin Version - 0.1.233 
IDE - Intellij 14.1.3 , JRE 1.8
Authentication – AAD Authentication

Steps -
Right Click Azure.
Click Manage Subscriptions.
Click Sign in.
Give user id.
Give password.
Unselect  the check box ‘Keep me signed in’.
Click ‘Sign in’.
Close the Manage Subscriptions window.
Plugin throwing exception while loading Mobile services, virtual machines and storage.
![exception](https://cloud.githubusercontent.com/assets/10046647/8184838/478a11e6-145e-11e5-9eff-f9123da62a65.png)

**Comment by avranju** [comment]
Babu to verify that this is the right build and confirm that it repros.

**Comment by kasturiswain** [comment]
Not able to repro in AD auth refactoring code.
