### ISSUE TITLE
plug in is throwing exception while selecting any premium storage account 

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#351]
<b>Environment: </b>
OS - Windows
Plugin Version - 0.1.233  and  0.1.36
IDE – Android Studio 1.2.2 , JRE 1.8
Authentication - Publish Settings file
<b>Steps -</b>
Click Azure.
Expand Storage.
Click on any premium storage account. 
It is throwing Exception as below.
![premium](https://cloud.githubusercontent.com/assets/10046647/8184891/9da66e6c-145e-11e5-979f-71d35aa1e5df.png)

**Comment by akrakovsky** [comment]
I removed Premium Storage Accounts from the list of Storage Accounts because they are not supported by the Azure SDK. I checked with @PabloZaiden, and Visual Studio does not list them either.

**Comment by ramkumargtv** [comment]
The premium account is not listed in the list of  Storage accounts in the latest plugin, closing this ticket
