### ISSUE TITLE
Plug in throwing exception while creating a new blob container

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#356]
<b>Environment: </b>
OS - Windows
Plugin Version - 0.1.36
IDE - Intellij 14.1.3 , JRE 1.8
Authentication - AAD Authentication

<b>Steps -</b>
Click Azure.
Expand Storage.
Expand one storage account. 
Right Click on Blobs.
Click create new container.
Plugin throwing IllegalComponentStateException.
PFB the screen shot.
![newcontainerexception](https://cloud.githubusercontent.com/assets/10046647/8249997/535605c6-168d-11e5-9716-78cc442a5e7e.png)

**Comment by omendrapandey** [comment]
This issue doesn't exist in plugin version 0.1.240
