### ISSUE TITLE
Review hard coded sleep in `MobileServiceRestManager.executePollRequest`

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#363]
There's a 2 second Thread.sleep in the `executePollRequest` method in the `MobileServiceRestManager` class. Two seconds seems like a really long wait. I wonder if we should perform the  Thread.sleep  only in response to a "too many requests received" error. Or maybe just reduce the sleep duration?

**Comment by martinsawicki** [comment]
obsolete
