### ISSUE TITLE
sign in failed on Ubuntu 15.04

### ISSUE THREAD

**Issue by saintxzm** [MSOpenTech/msopentech-tools-for-intellij#373]
Environment: 
OS – Ubuntu 15.04
Plugin Version - 0.1.255
IDE - Intellij Community Edition 14.1.4, JRE 1.8.0_51-b16 amd64
Authentication - sign in

![sign-in-dialog-after-sign-in-completes](https://cloud.githubusercontent.com/assets/13550197/9000301/b34cc996-3777-11e5-837e-c9ec41a06953.PNG)
![error-after-close-sign-in-dialog](https://cloud.githubusercontent.com/assets/13550197/9000302/b34f6228-3777-11e5-8c2b-6967e55bbfd5.PNG)
![error-in-terminal](https://cloud.githubusercontent.com/assets/13550197/9000321/017b7b44-3778-11e5-8851-8030b1b9e3f6.PNG)
![restart-subscriptions-management](https://cloud.githubusercontent.com/assets/13550197/9000329/267cad5a-3778-11e5-9832-40629f95d8d9.PNG)

Close error dialog, the UI will hang.
Restart IntelliJ and manage subscriptions again, the button shows sign out but without any subscription.

**Comment by ramkumargtv** [comment]
Cannot reproduce this issue on Ubuntu 15.04 machine .

**Comment by BeatriceOltean** [comment]
To close with the next release that has the fix
