### ISSUE TITLE
Class Not Found Error on Latest version of IntellijIDEA

### ISSUE THREAD

**Issue by dgilling** [MSOpenTech/msopentech-tools-for-intellij#382]
Get an error for class not found on latest version of IntellijIDEA 15.0.2. Does anyone else see same issue?
Using JDK 1.8
![error](https://cloud.githubusercontent.com/assets/9476006/11970966/e495f4d0-a8e9-11e5-8dcf-012b9ac706c5.png)

**Comment by martinsawicki** [comment]
From what we can tell, IntelliJ 15.0.2 changed something in its API that broke some existing plugins, including this one. 
Note though that this MSOpenTech plugin has now been deprecated in favor of the newer versions released by MS very recently. They are equivalent in functionality, it's just that the original msopentech plugin got split into 3 -- one for Android devs, one for Java devs on Azure, and one with Azure Explorer functionality:
https://plugins.jetbrains.com/plugin/8052
https://plugins.jetbrains.com/plugin/8053
https://plugins.jetbrains.com/plugin/8077

Depending on what you need, these are the plugins to choose from now. Note that the Azure Services Explorer plugin is currently a required pre-req for the other two, so start with that one, and then install whichever of the other two you need.

We have tested and made to work the 3 new ones on intelliJ 15.
We will be removing the MSOpenTech one soon.

**Comment by martinsawicki** [comment]
since this issues got fixed in the latest releases, closing.
