### ISSUE TITLE
Office 365 related errors are too generic

### ISSUE THREAD

**Issue by leotilli** [MSOpenTech/msopentech-tools-for-intellij#41]
If the OrgID does not have access to an Office365 service selected in the O365 activity template
The user gets the following error: 
![officeerrornopriviledges](https://cloud.githubusercontent.com/assets/926089/4786733/8227a67c-5d63-11e4-814e-00e7673a1b5b.png)

We should detect the Azure Office365 ones and return a more usable error message. In this case ""Insufficient privileges to complete the operation"

**Comment by BeatriceOltean** [comment]
Hi Leo, did Office365 has the fix now and therefore we can ship this with Jan milestone?

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
