### ISSUE TITLE
Verify and enhance error message when creating new tables

### ISSUE THREAD

**Issue by leotilli** [MSOpenTech/msopentech-tools-for-intellij#53]
From conversation on issue #47:

This is not showing proper error message when the user enters any non existing table.
PFB the screen shot.
![table](https://cloud.githubusercontent.com/assets/6553800/5294825/b995c13c-7b83-11e4-9598-6fe42a94bac9.png)

**Comment by kasturiswain** [comment]
This issue still persist in the latest build.
PFB the screen shot.
![schedulejob](https://cloud.githubusercontent.com/assets/10046647/5661912/7dc11428-9757-11e4-94d5-f24fcadeeb29.png)

**Comment by BeatriceOltean** [comment]
Would you please check to see the create table behavior first?

**Comment by kasturiswain** [comment]
Create table is working as expected.
