### ISSUE TITLE
Azure service management calls fail if underlying AD access token has expired

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#57]
When we use AD sign-in for managing Azure subscriptions the plugin uses cached copies of AD access tokens to authenticate calls to the Azure service management API. Sometimes, like when you haven't run the IDE for a day or two, the cached AD access token expires. In this case, during the next launch, the service explorer tool window pops up an error such as this:

> ![image](https://cloud.githubusercontent.com/assets/628128/5446587/cebba310-8475-11e4-9e72-e3207dc0387f.png)

The Azure API returns HTTP status code 400 (bad request) instead of 401 (unauthorized). We should perhaps handle status code 400 as though it were a 401 and attempt acquiring fresh tokens via the refresh token. Or at the very least, handle this error and pop up a more user friendly error message that suggests the user to try clearing out the subscription in the manage subscriptions window and try signing in again.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
