### ISSUE TITLE
Not able to install plug-in in intelliJ on ubuntu machine

### ISSUE THREAD

**Issue by selvamohandoss** [MSOpenTech/msopentech-tools-for-intellij#58]
<b> Environment </b> :  Ubuntu 12.04, IntelliJ 14.0.2 

Not able to install latest plug-in on Ubuntu,It  throws the error message.
PFB the screen shot.
![ubuntu_plugin](https://cloud.githubusercontent.com/assets/6553800/5453685/be85253c-8521-11e4-96e8-c7ae7413dc13.png)

**Comment by kasturiswain** [comment]
Able to install the production version.
Throwing  exception in private branch in git hub.
