### ISSUE TITLE
Not able to install Plug-in in Android Studio on Ubuntu OS

### ISSUE THREAD

**Issue by selvamohandoss** [MSOpenTech/msopentech-tools-for-intellij#60]
<b>Environment </b>: Ubuntu 12.04, Android Studio 1.0.1

Not able to install latest plug-in on Ubuntu,It throws the error message.
PFB the screen shot.
![erroras](https://cloud.githubusercontent.com/assets/6553800/5470402/07bfc2a8-85df-11e4-92ce-ae2f61031f06.png)

**Comment by avranju** [comment]
I am not able to reproduce the issue.

**Comment by kasturiswain** [comment]
Able to install the production version.
Throwing exception in private branch in git hub.
