### ISSUE TITLE
Mobile Services Wizard does not catch faulty passwords

### ISSUE THREAD

**Issue by ysxu** [MSOpenTech/msopentech-tools-for-intellij#72]
I created a new mobile service with the creation wizard with an existing database but entered the wrong password. The wizard does not prompt the error, proceeds on with the service creation, and simply doesn’t configure a database which leaves the service “unhealthy” in the portal. It took a while for me to figure out what was wrong since there weren't any proper error messages.
![screen shot 2015-01-05 at 11 19 14 am](https://cloud.githubusercontent.com/assets/1403654/5637009/2ca104b0-95ac-11e4-820d-b40844267e27.png)

**Comment by BeatriceOltean** [comment]
This is a dupe. There is no API error for this. Investigating... Now it creates a service in an unhealthy state..

**Comment by leotilli** [comment]
Right after we create the mobile service we perform a status request. If the status is any other than Healthy, we erase it; this is the same behavior than in Visual Studio.
I've tested this, creating a mobile service with wrong db password, both from the new Azure Services Activity wizard, and the Service Explorer, and it's working as expected (using our current dev branch).
If you see an unhealthy mobile service in the portal, you should wait for the process to complete in IntelliJ, probably with an error message explaining the cause of failure. If you then refresh the portal, the unhealthy mobile service should be deleted.

**Comment by kasturiswain** [comment]
This is working as expected as per @leo.
