### ISSUE TITLE
Enhancements to Mobile Services Wizard

### ISSUE THREAD

**Issue by ysxu** [MSOpenTech/msopentech-tools-for-intellij#73]
- If you are to create a new mobile service through the “Add Microsoft Service Wizard”, it is defaulted to a javascript backend and the button looks like it gets stuck – there is no progress bar or a “your service is being created” note till the creation window magically disappears, in which case the service is assumed to be successfully created. Users should be informed of the progress.
- Even if users enable push in the wizard, users have to manually enable enhanced push in the portal as of now. This process should be automated.
- Users need to manually enter the linked mobile service’s connection string and notification hub name. This process should be automated following the above item.
- (nice-to-have) Signing in to Azure account upon adding a Microsoft Mobile Services Activity prompts another sign in page with Visual Studio (I don’t know if it is possible for us to combine the log in?)

**Comment by BeatriceOltean** [comment]
1. it is a usability issue and we need to add animation 
2. Looking into the enhanced push 
3. Please provide details for what can be automated . There IS code generation in both cases now. How can that be improved?
4. This is the same experience as in VS. The Azure AD API force us to have this behavior
4.

**Comment by ysxu** [comment]
I see.
In terms of item 3, the wizard at one point, after I created a mobile service in the wizard, for me to enter the mobile service connection string and notification hub name. I was copy/pasting these info from the portal to the mobile service creation wizard (meaning I needed my portal open). The user experience would be nicer if this step is automated though I don't know if it is possible in legal/security terms?

**Comment by BeatriceOltean** [comment]
We need to populate the choices for the mobile service connection string and notification hub name. Let's keep it for Feb milestone

**Comment by leotilli** [comment]
We should evaluate how to integrate Enhanced Push, that is part of Mobile Services and should be configured automatically with it, vs Notification Hub, that is a different application and requires the name and key as input (we should evaluate if we can list existing hubs the same way we are doing for mobile services, and retrieving this data from there).

**Comment by ysxu** [comment]
Sounds great. Let me know if I can be of any help.

**Comment by martinsawicki** [comment]
obsolete
