### ISSUE TITLE
Mobile Services Wizard should be updated to Mobile Services 2.0 Beta SDK

### ISSUE THREAD

**Issue by ysxu** [MSOpenTech/msopentech-tools-for-intellij#74]
It's currently pulling 1.1.5 into users' projects.

**Comment by BeatriceOltean** [comment]
Need jar file

**Comment by ysxu** [comment]
beta-2.0 is now published to jCenter at https://bintray.com/azuremobileservices/SDK/Mobile-Services-Android-SDK/2.0-beta/view/general (jar file can be found here). the project can technically pull in 
compile 'com.microsoft.azure/azure-mobile-services-android-sdk/2.0-beta'
in its app gradle build file.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
