### ISSUE TITLE
VM listing fails in service explorer when switching authentication from subscription file to A/D auth

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#75]
VM listing fails in the following scenario:

1. Import an Azure subscription settings file and list VMs.
2. Open "Manage Subscriptions" window and clear subscriptions.
3. Then sign-in to an Azure subscription using active directory authentication.
4. Close "Manage Subscriptions" window.

Now you'll see that VM listing fails with a certificate error.

**Comment by kasturiswain** [comment]
This is working as expected in the latest build.
