### ISSUE TITLE
Sign in error using A/D Authentication 

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#82]
Able to do the activities (restart, shut down, start) when add the subscription using the publish setting file, but not able to do the activities while sign in the subscription.Sign in using A/D Authentication is not working fine.
PFB the screen shot.
![signinerrorissue3](https://cloud.githubusercontent.com/assets/10046647/5699377/2680e470-9a4c-11e4-9da8-49a822281d7c.png)

**Comment by avranju** [comment]
This appears to be a bug in the Azure SDK for Java. I have submitted a new issue to their repo [here](https://github.com/Azure/azure-sdk-for-java/issues/458).

**Comment by kasturiswain** [comment]
This issue is still reproducible in the latest build.
PFB the screen shot.
![82](https://cloud.githubusercontent.com/assets/10046647/5753267/2c185b9a-9cac-11e4-960d-54ade8350ffe.png)

**Comment by avranju** [comment]
The problem was that the automated build script still referred to the Azure SDK jars from Maven Central instead of the custom built ones in the repo. The script has been updated now and the next build should have the right jars.

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
