### ISSUE TITLE
Manage VM activities different in story board and different in plug in

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#84]
In Android Storyboard we had the following VM Management Options.
        Refresh
        Delete
        Connect Remote Desktop
        Shutdown
        Restart
        Configure
        Enable Debugging
 
    But in the Build Plugin we are getting the following VM Management Options.
        Delete
        Download RDP file
        Shutdown
        Start
        Restart
        Refresh

**Comment by BeatriceOltean** [comment]
The Configure and Enable debugging will be implemented with FebX release

**Comment by avranju** [comment]
Visual Studio has separate buttons for *Shutdown*, *Start* and *Restart*. I think it makes sense for us to retain those options.

**Comment by kasturiswain** [comment]
In plugin the button the ''Download RDP file" should be "Connect Remote Desktop".

**Comment by avranju** [comment]
The change wasn't merged in last night's build. Please check in tonight's build.

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
