### ISSUE TITLE
Manage Subscriptions window Issue

### ISSUE THREAD

**Issue by kasturiswain** [MSOpenTech/msopentech-tools-for-intellij#85]
In story board we have the button Name as "Manage Subscriptions" where as in the plugin the button name is "manage Subscription".
In story board we have "Filter By Subscription" where as in plugin it is "Subscriptions".
PFB the screen shot.

![pluginui](https://cloud.githubusercontent.com/assets/10046647/5701530/6261bc3c-9a72-11e4-91ce-ad97c6a2cfbe.png)
![storyboardui](https://cloud.githubusercontent.com/assets/10046647/5701534/720f40be-9a72-11e4-938e-cd31ddb3c79e.JPG)

**Comment by BeatriceOltean** [comment]
Just text change. The default should enable all of the subscriptions.

**Comment by kasturiswain** [comment]
The button name is "Import Subscription" in steed of "Import Subscriptions".
PFB the screen shot.
![85](https://cloud.githubusercontent.com/assets/10046647/5753180/d90d470e-9caa-11e4-82ad-8ba1cc22d426.png)

**Comment by leotilli** [comment]
The current fix enables all options whenever we open the manage subscription screen, it should remember the selected subcriptions and only enable by default after importing.

**Comment by kasturiswain** [comment]
This issue is fixed and working as expected in the latest build.
