### ISSUE TITLE
Entering an invalid file path in import subscriptions dialog should show error message when clicking "Import"

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/msopentech-tools-for-intellij#96]
Currently, if you enter an invalid file path (i.e. a file path that doesn't point to a valid file) in the "File Location" text box in the "Import Microsoft Azure Subscriptions" dialog and then proceed to click the "Import" button, nothing happens. The dialog just ignores the click. It might make sense to show a suitable message to the user instead.

**Comment by kasturiswain** [comment]
This issue if fixed and working as expected in the latest build.
